//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimChomSao.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimChomSao.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i1 {
            get {
                object obj = ResourceManager.GetObject("i1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i10 {
            get {
                object obj = ResourceManager.GetObject("i10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i11 {
            get {
                object obj = ResourceManager.GetObject("i11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i12 {
            get {
                object obj = ResourceManager.GetObject("i12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i2 {
            get {
                object obj = ResourceManager.GetObject("i2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i3 {
            get {
                object obj = ResourceManager.GetObject("i3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i4 {
            get {
                object obj = ResourceManager.GetObject("i4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i5 {
            get {
                object obj = ResourceManager.GetObject("i5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i6 {
            get {
                object obj = ResourceManager.GetObject("i6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i7 {
            get {
                object obj = ResourceManager.GetObject("i7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i8 {
            get {
                object obj = ResourceManager.GetObject("i8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i9 {
            get {
                object obj = ResourceManager.GetObject("i9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo Bình (20/1 – 18/2): Kiên định, hết mình trong tình yêu nhưng cũng lý trí, tỉnh táo không kém.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thần Nông (24/10 – 22/11): “Khẩu xà tâm Phật”, cảm xúc cực đoan.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Mã (23/11 – 21/12): Luôn cảm thấy cô đơn giữa vòng tròn bè bạn.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma Kết (22/12 – 19/1): Nội tâm dữ dội ẩn sau vẻ ngoài lạnh lùng.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Ngư (19/2 – 20/3): Nhạy cảm, thánh thiện, sợ hãi sự cô đơn.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạch Dương (21/3 – 19/4): Chính trực, nghĩa khí, ấm áp.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kim Ngưu (20/4 – 20/5): Thật thà, lương thiện, dễ mềm lòng, hướng nội.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Tử (21/5 – 21/6): “Tự kỷ”, hài hước, yêu thương cuồng nhiệt.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cự Giải (22/6 – 22/7): Nhạy cảm, trọng thể diện, giàu đức hi sinh.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sư Tử (23/7 – 22/8): Kiêu hãnh, dứt khoát, “cư xử đẹp” với bạn bè.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử Nữ (23/8 – 23/9): Rất sợ cô đơn.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiên Bình (24/9 – 23/10): Thanh lịch, công bằng, cần có người đồng hành.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có Bảo Bình ở cạnh đồng nghĩa với việc “làm bạn” cùng những cảm giác mới mẻ, vui tươi. Bảo Bình có tính cách khá tùy hứng, bốc đồng nhưng đứng trước tình bạn, tình yêu, họ có thể trở thành một người kiên nhẫn, cố chấp đến khó hiểu. Một khi đã trao tình cảm cho ai, đừng hòng Bảo Bình bỏ cuộc, chạy trốn, chia li dù đối phương chẳng còn yêu mình. Họ cũng chẳng ngại ngần việc để lộ tâm trạng yếu đuối si tình trước mặt người khác.
        ///
        ///Si tình là vậy nhưng Bảo Bình luôn biết đâu là giới hạn của mình. Khi cảm thấy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu cảm giác an toàn, sợ tổn thương, vậy nên khi ngủ Thần Nông hầu như chẳng lúc nào rời xa thú bông hay chiếc gối ôm mềm mại. Đừng để vẻ bề ngoài ghê gớm, kiên cường của họ đánh lừa, đó thực chất chỉ là lớp vỏ ngụy trang cho một nội tâm yếu đuối, nhạy cảm. Thế giới riêng của một Thần Nông có đủ mọi loại cung bậc cảm xúc từ hạnh phúc tột cùng để bi thương cực đỉnh.
        ///
        ///Thần Nông là kiểu người “khẩu xà tâm Phật”, thường buông lời lẽ cay độc dù trong lòng yêu mến, trân trọng vô cùng. Họ là người hiểu chuyện, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bẩm sinh đã có nhân duyên tốt, Mã Mã lại càng được mọi người yêu quý nhờ sự “mồm mép”, láu cá của mình. Nhân Mã hào phóng, yêu tự do, thích giao tiếp nên cảm giác mà họ ghét bỏ nhất là khi phải một mình trơ trọi cô đơn ở một nơi trống trải. Nhiều bạn bè là thế nhưng mỗi khi gặp chuyện, Nhân Mã thường chỉ biết một mình gặm nhấm nỗi buồn. Đau đến nhỏ máu, họ vẫn sẽ gắng gượng mỉm cười.
        ///
        ///Khi bắt đầu một đoạn tình cảm, Nhân Mã đào hoa thường chỉ trao đi một phần nhỏ con tim mình. Trải qua một khoảng thời gian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma Kết thích được “một mình một thế giới” để mặc sức ngẫm nghĩ về cuộc sống. Những biến động trong thế giới nội tâm của một Ma Kết thường đến bất chợt và mỗi khi xuất hiện đều khá dữ dội. Họ có thể đang vui tươi đột nhiên trở nên trầm mặc vì một ý nghĩ thoáng qua, để rồi lại có thể bất chợt cười vui rạng rỡ.
        ///
        ///Ma Kết có tấm lòng lương thiện, biết cảm thông. Họ luôn đem lại cảm giác an toàn, đáng tin cậy cho người đối diện. Ma Kết cũng thích những thứ khiến trái tim băng giá cô đơn của họ trở nên ấm áp, đượ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t12 {
            get {
                return ResourceManager.GetString("t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Ngư là cung Hoàng đạo cực kỳ nhạy cảm. Họ có khả năng nhận thức mọi thay đổi dù nhỏ bé tinh tế nhất nhờ giác quan thứ Sáu cực nhạy. Song Ngư ghét sự giả dối nhưng lòng tốt vô hạn không cho phép họ từ chối bất cứ ai dù lí trí có nghi ngờ.
        ///
        ///Chinh phục thành công trái tim Song Ngư, bạn sẽ có được một người yêu tận tụy, sẵn sàng thay đổi bản thân vì tình yêu của mình. Tuy nhiên hãy chủ động từ bỏ nếu ngay từ đầu bạn đã không có ý định gắn bó với họ lâu dài, Song Ngư với tâm hồn trong sáng, ngây thơ không [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạch Dương vốn là người thẳng thắn, chân thật, chẳng bao giờ biết “ủ mưu”. Họ thường rất nghiêm túc trong chuyện tình cảm và coi trọng thể diện. Sợ hãi sự cô đơn, Bạch Dương luôn gắn bó với gia đình, thích thú dùng sự hài hước của mình khiến mọi người vui vẻ.
        ///
        ///Có đôi khi, ẩn sau nụ cười của Bạch Dương không thực sự là niềm vui. Họ dùng khuôn mặt cười để che giấu tất cả. Họ không muốn bất cứ ai phải lo lắng, cũng không cần bất kỳ sự đồng cảm hay thương xót nào. Những lúc đó, bạn nên dành tặng họ một cái ôm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kim Ngưu thuộc tuýp người luôn bày tỏ mọi cảm xúc của mình ra ngoài không giấu diếm. Tuy nhiên cách thể hiện cảm xúc của họ thường không khéo léo, không mềm mại, khiến mọi người khó chịu hoặc hiểu lầm. Mỗi khi cãi nhau, lời nói của Kim Ngưu có thể làm tổn thương đối phương đến cực điểm. Khi vui vẻ, người ta sẽ thấy Kim Ngưu nói nói cười cười nhưng một khi đã tức giận rồi thì một câu họ cũng chẳng thèm mở miệng.
        ///
        ///Điểm yếu lớn nhất của Kim Ngưu là dễ mềm lòng. Chỉ cần đối phương chịu cúi đầu nói xin lỗi và  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sinh ra dưới cung Song Tử thường trưởng thành rất sớm. Họ có sở thích khá “dị” đó là được ở một mình. Chỉ khi một mình, Song Tử mới cảm thấy thoải mái, vui vẻ, mặc sức “tự kỷ”, suy tư. Chính tính cách lạ lùng này khiến cho nhiều người cảm thấy Song Tử thật cô đơn, cô độc.
        ///
        ///Song Tử là người có nhiều mong muốn trong tình yêu nhưng lại biết cách che giấu những mong mỏi đó của mình. Chính vì lẽ đó mà họ thường bị hiểu lầm là giả dối, chỉ người trong cuộc mới biết họ luôn là người trao đi chân tình như [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vì tự ti nên trong chuyện tình cảm Cự Giải rất dễ bị tổn thương. Nhưng họ cũng chính là mẫu người có thể vì một chuyện siêu bé nhỏ giản đơn mà cảm thấy hạnh phúc, thỏa mãn. Cự Giải rất khó mở lòng, đặt trọn niềm tin và tình yêu ở một người. Họ dễ xúc động, mau nước mắt và một khi đã rơi vào trạng thái bi thương sầu thảm thì rất khó thoát ra. Họ sẵn sàng hy sinh bản thân vì người khác, dốc sức dốc lòng vì một mối quan hệ.
        ///
        ///Đây còn là những người không thích qua lại với người có tính cách và nhân phẩm không [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sư Tử rất ngại việc phải lựa chọn hoặc đưa ra quyết định. Họ thích nghe ý kiến và những phân tích đánh giá của bạn bè về một vấn đề sau đó mới quyết theo cách của mình. Điểm khác biệt giữa Sư Tử và Thiên Bình đó là một khi đã quyết sẽ chẳng có ai hay điều gì có thể làm Sư Tử hồi tâm chuyển ý.
        ///
        ///Nụ cười của người thuộc cung Sư Tử giản đơn, chân thành, thuần khiết nhất trên đời. Họ luôn cư xử với mọi người bằng thái độ tích cực trong khi những đau thương Sư Tử giữ lại cho mình. Rất ít người có may mắn được t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vẻ ngoài lạnh lùng, trầm mặc, ghê gớm nhưng kỳ thực Xử Nữ là người có nội tâm đặc biệt sâu sắc, chung thủy, căm ghét sự phản bội. Với kẻ thù, cung Hoàng đạo này không bao giờ nương tay nhưng khi ở cạnh những người yêu thương, họ lại hay hoài nghi, bất an, thiếu tự tin. Xử Nữ cũng hay có thói quen soi mói, xét nét chỉ trích khá cay nghiệt. Tuy vậy, họ là người “khẩu xà tâm phật”, không đối tốt với bạn sẽ chẳng có chuyện họ phê phán gay gắt đến thế. Xử Nữ không thích gần gũi người lạ, nhưng đối với người thân [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiên Bình trời sinh đã sở hữu vẻ ngoài nho nhã cùng tài năng ưu việt, bản thân họ cũng thích được mọi người ngưỡng mộ, tán dương. Thiên Bình hầu như chẳng bao giờ tranh giành, cướp giật của ai thứ gì, cũng chẳng bày tỏ sự tức giận, cay cú khi món đồ thuộc quyền sở hữu bị người khác tước đoạt. Với họ, những hành động cũng như cảm xúc đó thật yếu đuối, đáng xấu hổ và một khi thể hiện ra ngoài sẽ ngay lập tức phá hủy hình tượng ổn định, thanh tao mà họ xây dựng cho mình.
        ///
        ///Thiên Bình làm gì cũng muốn có bạn  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
    }
}
